# Generated by Django 5.2.5 on 2025-09-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
