# Generated by Django 4.2.1 on 2025-11-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_class_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lecture_date',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='class_field',
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='teacher.class')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teacher.lecture'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='lecture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='teacher.lecture'),
        ),
    ]
