# Generated by Django 4.2.1 on 2025-11-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_class_subject_remove_class_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='class_obj',
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='teacher.subject'),
        ),
    ]
