# Generated by Django 4.2.1 on 2025-11-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_lecture_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='teacher.lecture'),
        ),
    ]
