# Generated by Django 4.2.1 on 2025-11-16 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0008_alter_qrcode_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., '2025-2026'", max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this is the current, active session.')),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text="e.g., 'First Year'", max_length=255),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Student'}, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text="e.g., 'B.Sc. Computer Science'", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text="e.g., 'Introduction to Programming'", max_length=255),
        ),
        migrations.AddField(
            model_name='class',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='teacher.academicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('course', 'name', 'session')},
        ),
    ]
