# Generated by Django 4.2.1 on 2025-11-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_academicsession_alter_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='teacher.academicsession'),
        ),
    ]
