# Generated by Django 4.2.1 on 2025-11-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_class_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAttendance',
            fields=[
            ],
            options={
                'verbose_name': 'Historical Attendance Record',
                'verbose_name_plural': 'Historical Attendance Records',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('teacher.attendance',),
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Set to true to hide from active lists.'),
        ),
        migrations.AlterField(
            model_name='class',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='teacher.academicsession'),
        ),
    ]
