# Generated by Django 4.2.1 on 2025-11-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
