# Generated by Django 4.2.1 on 2025-12-05 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_attendance_rejection_reason_attendance_status'),
        ('student', '0002_customuser_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.course'),
        ),
    ]
